### ISSUE TITLE
[Bug]: crash if using /class bind

### ISSUE THREAD

**Issue by Hitman477** [magemonkeystudio/fabled#921]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried to reproduce this without OP?

- [X] I have tested without OP

### Current Behavior

if i use /class bind with item in hand,without name of the skill, it will crash

### Expected Behavior

everything goes fine

### Steps To Reproduce

1. pick item in hand
2. use /class bind (without skill)
3. crash

### Environment

```markdown
- Server Software: paper 1.21.1 Leaf
- Fabled Version: fabled-1.0.1-R0.6-20240917.023949-1
- Codex Version: codex-1.0.1-R0.3-20240917.024013-1
- Divinity Version: divinity-1.0.1-R0.3-20240924.052643-1
- Plugins:
[16:06:37] [ServerMain/INFO]: [PluginInitializerManager] Initialized 25 plugins
[16:06:37] [ServerMain/INFO]: [PluginInitializerManager] Paper plugins (3):
 - Codex (1.0.1-R0.3-SNAPSHOT), Divinity (1.0.1-R0.3-SNAPSHOT), Fabled (1.0.1-R0.6-SNAPSHOT)
[16:06:37] [ServerMain/INFO]: [PluginInitializerManager] Bukkit plugins (22):
 - BetonQuest (2.1.3), Chatty (2.19.14), CinematicStudio (2.0.1-indev-1), Citizens (2.0.35-SNAPSHOT (build 3583)), DecentHolograms (2.8.11), Essentials (2.20.1), FastAsyncWorldEdit (2.11.3-SNAPSHOT-930;7192e14), ImageFrame (1.7.10.0), InteractionVisualizer (1.18.11.1), LoneLibs (1.0.59), LuckPerms (5.4.141), ModelEngine (R4.0.7), MythicMobs (5.7.2-${CI_COMMIT_SHORT_SHA}), PlaceholderAPI (2.11.7-DEV-200), ProtocolLib (5.3.0-SNAPSHOT-732), SkinsRestorer (15.4.3), TAB (4.1.8), Towny (0.100.4.0), Vault (1.7.3-b131), ViaBackwards (5.0.3), ViaVersion (5.0.3), WorldGuard (7.0.12+829a4a4)
```

### latest.log

<details><summary>latest.log</summary>
<p>

```log
[21:21:01] [Server thread/INFO]: CXMorgan issued server command: /class bind
[21:21:01] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.ExceptionInInitializerError: null
	at fabled-1.0.1-R0.6-20240917.023949-1.jar/studio.magemonkey.fabled.cmd.CmdBind.execute(CmdBind.java:118) ~[fabled-1.0.1-R0.6-20240917.023949-1.jar:?]
	at codex-1.0.1-R0.3-20240917.024013-1.jar/studio.magemonkey.codex.mccore.commands.ConfigurableCommand.execute(ConfigurableCommand.java:547) ~[codex-1.0.1-R0.3-20240917.024013-1.jar:?]
	at codex-1.0.1-R0.3-20240917.024013-1.jar/studio.magemonkey.codex.mccore.commands.ConfigurableCommand.execute(ConfigurableCommand.java:554) ~[codex-1.0.1-R0.3-20240917.024013-1.jar:?]
	at codex-1.0.1-R0.3-20240917.024013-1.jar/studio.magemonkey.codex.mccore.commands.ConfigurableCommand.execute(ConfigurableCommand.java:517) ~[codex-1.0.1-R0.3-20240917.024013-1.jar:?]
	at io.papermc.paper.command.brigadier.bukkit.BukkitCommandNode$BukkitBrigCommand.run(BukkitCommandNode.java:86) ~[leaf-1.21.1.jar:1.21.1-DEV-3eb1410]
	at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.3.10.jar:?]
	at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:28) ~[leaf-1.21.1.jar:1.21.1-DEV-3eb1410]
	at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:13) ~[leaf-1.21.1.jar:1.21.1-DEV-3eb1410]
	at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8) ~[leaf-1.21.1.jar:1.21.1-DEV-3eb1410]
	at net.minecraft.commands.execution.CommandQueueEntry.execute(CommandQueueEntry.java:5) ~[leaf-1.21.1.jar:1.21.1-DEV-3eb1410]
	at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:101) ~[leaf-1.21.1.jar:1.21.1-DEV-3eb1410]
	at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:450) ~[leaf-1.21.1.jar:1.21.1-DEV-3eb1410]
	at net.minecraft.commands.Commands.performCommand(Commands.java:352) ~[leaf-1.21.1.jar:1.21.1-DEV-3eb1410]
	at net.minecraft.commands.Commands.performCommand(Commands.java:342) ~[leaf-1.21.1.jar:1.21.1-DEV-3eb1410]
	at net.minecraft.commands.Commands.performCommand(Commands.java:337) ~[leaf-1.21.1.jar:1.21.1-DEV-3eb1410]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.performUnsignedChatCommand(ServerGamePacketListenerImpl.java:2336) ~[leaf-1.21.1.jar:1.21.1-DEV-3eb1410]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$16(ServerGamePacketListenerImpl.java:2284) ~[leaf-1.21.1.jar:1.21.1-DEV-3eb1410]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[leaf-1.21.1.jar:1.21.1-DEV-3eb1410]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[leaf-1.21.1.jar:1.21.1-DEV-3eb1410]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[leaf-1.21.1.jar:1.21.1-DEV-3eb1410]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1573) ~[leaf-1.21.1.jar:1.21.1-DEV-3eb1410]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:190) ~[leaf-1.21.1.jar:1.21.1-DEV-3eb1410]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[leaf-1.21.1.jar:1.21.1-DEV-3eb1410]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1551) ~[leaf-1.21.1.jar:1.21.1-DEV-3eb1410]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1544) ~[leaf-1.21.1.jar:1.21.1-DEV-3eb1410]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[leaf-1.21.1.jar:1.21.1-DEV-3eb1410]
	at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1492) ~[leaf-1.21.1.jar:1.21.1-DEV-3eb1410]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1502) ~[leaf-1.21.1.jar:1.21.1-DEV-3eb1410]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1346) ~[leaf-1.21.1.jar:1.21.1-DEV-3eb1410]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[leaf-1.21.1.jar:1.21.1-DEV-3eb1410]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "java.lang.reflect.Method.setAccessible(boolean)" because "m" is null
	at codex-1.0.1-R0.3-20240917.024013-1.jar/studio.magemonkey.codex.util.Reflex.invokeMethod(Reflex.java:189) ~[codex-1.0.1-R0.3-20240917.024013-1.jar:?]
	at codex-1.0.1-R0.3-20240917.024013-1.jar/studio.magemonkey.codex.util.ItemUT.addSkullTexture(ItemUT.java:235) ~[codex-1.0.1-R0.3-20240917.024013-1.jar:?]
	at codex-1.0.1-R0.3-20240917.024013-1.jar/studio.magemonkey.codex.util.ItemUT.addSkullTexture(ItemUT.java:220) ~[codex-1.0.1-R0.3-20240917.024013-1.jar:?]
	at codex-1.0.1-R0.3-20240917.024013-1.jar/studio.magemonkey.codex.manager.api.menu.YAMLMenu.reload(YAMLMenu.java:90) ~[codex-1.0.1-R0.3-20240917.024013-1.jar:?]
	at codex-1.0.1-R0.3-20240917.024013-1.jar/studio.magemonkey.codex.manager.api.menu.YAMLMenu.<init>(YAMLMenu.java:35) ~[codex-1.0.1-R0.3-20240917.024013-1.jar:?]
	at fabled-1.0.1-R0.6-20240917.023949-1.jar/studio.magemonkey.fabled.api.binding.BindingMenu$1.<init>(BindingMenu.java:34) ~[fabled-1.0.1-R0.6-20240917.023949-1.jar:?]
	at fabled-1.0.1-R0.6-20240917.023949-1.jar/studio.magemonkey.fabled.api.binding.BindingMenu.<clinit>(BindingMenu.java:34) ~[fabled-1.0.1-R0.6-20240917.023949-1.jar:?]
	... 31 more
[21:21:01] [Server thread/ERROR]: This crash report has been saved to: G:\123\crash-reports\crash-2024-10-08_21.21.01-server.txt
[21:21:01] [Server thread/INFO]: Stopping server

```

</p>
</details>

**Comment by Travja** [comment]
Should be fixed with https://github.com/magemonkeystudio/codex/commit/4690eec788b37c101363bc5fab53bc74cf3da354
